# Generated by Django 5.0.4 on 2024-04-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order_product_ordermodel_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='email',
        ),
    ]
