# Generated by Django 5.0.4 on 2024-04-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_order_delete_product_remove_ordermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
