# Generated by Django 5.0.4 on 2024-05-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_is_served'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.IntegerField(max_length=15)),
                ('date', models.DateField()),
                ('person', models.IntegerField(max_length=2)),
            ],
        ),
    ]
