# Generated by Django 5.0.4 on 2024-05-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_is_served'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('B', 'Beverage'), ('D', 'Desserts'), ('P', 'Pastries'), ('M', 'Main')], max_length=2)),
                ('image', models.ImageField(upload_to='product')),
                ('prodapp', models.TextField(default='')),
            ],
        ),
    ]
