# Generated by Django 5.0.4 on 2024-05-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
    ]
