# Generated by Django 5.0.4 on 2024-05-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_book_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book_table',
        ),
    ]
