# Generated by Django 5.0.4 on 2024-05-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_orderitem'),
        ('customer', '0007_remove_product_prodapp'),
    ]

    operations = [
    ]
