# Generated by Django 5.0.4 on 2024-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_reservationmodel_delete_book_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='number',
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='person',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
