# Generated by Django 5.0.4 on 2024-05-06 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_reservationmodel_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
