# Generated by Django 5.0.4 on 2024-05-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_product_prodapp'),
        ('customer', '0009_reservationmodel_created_on'),
    ]

    operations = [
    ]
