# Generated by Django 5.0.4 on 2024-05-07 08:42

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_merge_20240506_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='time',
            field=models.TimeField(default=customer.models.default_time),
        ),
    ]
