# Generated by Django 5.0.4 on 2024-05-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_reservationmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
