# Generated by Django 5.0.4 on 2024-05-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_product_price'),
        ('customer', '0012_reservationmodel_is_served'),
    ]

    operations = [
    ]
