# Generated by Django 5.0.4 on 2024-05-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_merge_20240509_1514'),
        ('customer', '0013_merge_20240509_1515'),
    ]

    operations = [
    ]
