# Generated by Django 5.0.6 on 2024-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_cart_user_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
