# Generated by Django 5.0.6 on 2024-05-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_orderplaced_is_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
