# Generated by Django 5.0.4 on 2024-05-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customizationoption_product_customization_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationoption',
            name='description',
        ),
    ]
