# Generated by Django 5.0.6 on 2024-05-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_customer_address_alter_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='first name', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(default='media/default_image.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='first name', max_length=100),
        ),
    ]
