# Generated by Django 5.0.4 on 2024-05-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_customizationoption_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customization_options',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CustomizationOption',
        ),
    ]
