# Generated by Django 5.0.6 on 2024-05-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_remove_customer_address_customer_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
