# Generated by Django 5.0.6 on 2024-05-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points_required', models.IntegerField()),
                ('image', models.ImageField(upload_to='redemption_images/')),
            ],
        ),
    ]
