# Generated by Django 5.0.6 on 2024-05-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remark',
            field=models.TextField(default='Remark:', max_length=200),
        ),
    ]
