# Generated by Django 5.0.6 on 2024-05-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_product_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='remark',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
