# Generated by Django 5.0.6 on 2024-05-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_remove_product_remark_orderplaced_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
