# Generated by Django 5.0.6 on 2024-05-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_redeemeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemeditem',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
