# Generated by Django 5.0.6 on 2024-05-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_redeemeditem_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemeditem',
            name='is_verified',
        ),
    ]
