# Generated by Django 5.0.6 on 2024-05-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_remove_redeemeditem_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='food_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('served', 'Served')], default='pending', max_length=10),
        ),
    ]
