# Generated by Django 5.0.6 on 2024-05-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_orderplaced_food_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='status',
        ),
    ]
