# Generated by Django 5.0.6 on 2024-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_redemptionoption_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redemptionoption',
            old_name='review',
            new_name='review_required',
        ),
        migrations.AddField(
            model_name='redeemeditem',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
