# Generated by Django 5.0.6 on 2024-05-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_rename_review_redemptionoption_review_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemeditem',
            name='review',
        ),
    ]
