# Generated by Django 5.0.6 on 2024-06-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_remove_redeemeditem_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='method',
            field=models.CharField(choices=[('Dine In', 'Dine In'), ('Pick Up', 'Pick Up')], default='Pick Up', max_length=10),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
