# Generated by Django 5.0.6 on 2024-06-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_orderplaced_method_orderplaced_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='method',
            field=models.CharField(max_length=10),
        ),
    ]
