# Generated by Django 5.0.6 on 2024-06-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_alter_orderplaced_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(default='some_default_value', max_length=100),
        ),
    ]
