# Generated by Django 5.0.6 on 2024-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_alter_orderplaced_method_alter_orderplaced_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='method',
            field=models.CharField(max_length=10),
        ),
    ]
