# Generated by Django 5.0.6 on 2024-06-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_remove_orderplaced_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
