# Generated by Django 5.0.6 on 2024-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_orderplaced_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='method',
            field=models.CharField(choices=[('Dine In', 'Dine In'), ('Pick Up', 'Pick Up')], default='Dine In', max_length=10),
        ),
    ]
