# Generated by Django 5.0.6 on 2024-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_alter_orderplaced_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemeditem',
            name='claim_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='redeemeditem',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
