# Generated by Django 5.0.6 on 2024-06-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_redeemeditem_last_redeemed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemeditem',
            name='last_redeemed_date',
        ),
    ]
