# Generated by Django 5.0.6 on 2024-06-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_remove_redeemeditem_last_redeemed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
