# Generated by Django 5.0.4 on 2024-06-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_ad'),
        ('customer', '0045_remove_redeemeditem_last_redeemed_date'),
    ]

    operations = [
    ]
