# Generated by Django 5.0.4 on 2024-06-06 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_merge_20240605_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customizations',
            field=models.ManyToManyField(blank=True, to='customer.customizationchoice'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='customizations',
            field=models.ManyToManyField(blank=True, to='customer.customizationchoice'),
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_choice', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_options', to='customer.product')),
            ],
        ),
        migrations.AddField(
            model_name='customizationchoice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='customer.customizationoption'),
        ),
    ]
