# Generated by Django 5.0.6 on 2024-06-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_remove_ordermodel_items_remove_orderitem_item_and_more'),
        ('customer', '0047_customizationchoice_cart_customizations_and_more'),
    ]

    operations = [
    ]
