# Generated by Django 5.0.4 on 2024-06-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_additionalimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
